package vista;

import modelo.listaDoble;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.Icon;
import javax.swing.ImageIcon;

public class dibujos extends javax.swing.JPanel {
    String nombre;
    int cont=0;
    listaDoble listaDoble=new listaDoble();
    listaDoble tal = new listaDoble();
    listaDoble tp = new listaDoble();
    
    public dibujos(int cont,listaDoble listaDoble) {
        initComponents();
        this.setOpaque(true);
        this.setSize(new Dimension(20,1000));
        this.setPreferredSize(new Dimension(20, 1000));
       // this.setBackground(Color.LIGHT_GRAY);
        this.cont = cont;
        this.listaDoble=listaDoble;
    }
     public dibujos(int cont,listaDoble tal, listaDoble tp) {
        initComponents();
        this.setOpaque(true);
        this.setSize(new Dimension(20,1000));
        this.setPreferredSize(new Dimension(20, 1000));
        this.setBackground(Color.LIGHT_GRAY);
        this.cont = cont;
        this.tal = tal;
        this.tp = tp;
        
    }
    
//     public void paint(Graphics g){
//        super.paint(g);
//        g.setColor(Color.BLUE);        
//        int disNodo = 30, aumentoNodo = 80;
//        int disNombre = 40,aumentoNombre = 82;
//        
//        for (int i = 0; i < cont; i++) {
//            //g.drawImage(img.getImage(), disNodo, 35, 170, 50, this);
//            g.setColor(Color.BLUE);
//            
//            g.fillRect(50, disNodo, 160, 70);
//            disNodo += aumentoNodo;
//            
//            this.setSize(disNodo+200, 21);
//                                    
//            g.setColor(Color.black);
//            g.drawString(listaDoble.get(i).dato.getNombreProceso(), 30, disNodo);
//            
//            this.repaint();
//
//            disNombre += aumentoNombre;   
//        }
//    }
    
     public void paint(Graphics g){
      super.paint(g);
          int disNodo = 15, aumentoNodo = 75;       
        int disNombre = 20,aumentoNombre= 73; 
        int disNombreProceso = 50,aumentoNombreProceso= 80;
             g.setColor(Color.BLUE);
            g.fillRect(50, disNodo , 160, 70);
            this.setSize(disNodo+200, 21); 
            g.setColor(Color.black); 
            g.drawString("0", 30, disNombre);
            g.setColor(Color.white);   
            
            g.drawString("SO", 120, disNombreProceso);
            disNodo +=  aumentoNodo;
            disNombre += aumentoNombre;
            g.setColor(Color.GRAY);
            g.fillRect(50, disNodo , 160, 340);
            this.setSize(disNodo+200, 21); 
            g.setColor(Color.black);    g.drawString("10", 30, disNombre); 
            g.drawString("64", 30, 430);  
       
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
