package vista;

import modelo.listaDoble;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import sun.awt.windows.ThemeReader;

public class hilos extends javax.swing.JPanel {

    String nombre;
    listaDoble tal =new listaDoble();
    listaDoble tp = new listaDoble();
    
    public hilos(listaDoble tal, listaDoble tp) {
        initComponents();
        this.setOpaque(true);
        this.setSize(new Dimension(20,1000));
        this.setPreferredSize(new Dimension(20, 1000));
        this.tal = tal;
        this.tp = tp;
    }
    
    public void paint(Graphics g){
    super.paint(g);
    
        //Pintando los rectangulos azules de los procesos tp
        int disNodo = 15, aumentoNodo = 75;       
        int disNombre = 20,aumentoNombre= 73; 
        int disNombreProceso = 50, aumentoNombreProceso= 80;
            g.setColor(Color.BLUE);
            g.fillRect(50, disNodo , 160, 70);
            this.setSize(disNodo+200, 21); 
            g.setColor(Color.black); 
            g.drawString("0", 30, disNombre);
            g.setColor(Color.white);   
            g.drawString("SO", 120, disNombreProceso);
            disNodo +=  aumentoNodo;
            disNombre += aumentoNombre;
            g.setColor(Color.GRAY);
            g.fillRect(50, disNodo , 160, 340);
            this.setSize(disNodo+200, 21); 
            g.setColor(Color.black);    g.drawString("10", 30, disNombre); 
            g.drawString("64", 30, 430);            
           
            disNodo = 90;
            aumentoNodo = 75;       
            disNombre = 93;
            aumentoNombre= 73;
            
        for (int i = 0; i < tp.size(); i++) {  
           char aux = 't';
           
//            for(int j = 1; j < tp.size(); j++){
//            if(tp.get(i).dato.getLocalidad() == tp.get(j).dato.getLocalidad())
//                aux = 'f';
//            }

            if(aux == 't'){
            if(tp.get(i).dato.getEstado()== 'A')
                g.setColor(Color.BLUE);
            else
               g.setColor(Color.RED); 
            g.fillRect(50, disNodo , 160, 70);
            disNodo += aumentoNodo;
            this.setSize(disNodo+200, 21); 
            g.setColor(Color.black); 
            
            g.drawString(String.valueOf(tp.get(i).dato.getLocalidad()), 30, disNombre);
            this.repaint();
            disNombre += aumentoNombre;
            g.drawString(String.valueOf(tp.get(i).dato.getLocalidad()+tp.get(i).dato.getTama()), 30, disNombre);
            }             
        }
        //Pintando los rectangulos grices y rojos de los espacios de tal 
//         disNodo = 30;
//         aumentoNodo = 80;       
//         disNombre = 40;
//         aumentoNombre= 82;
//        for (int i = 0; i < tal.size(); i++) {
//            
//            g.setColor(Color.BLUE);
//            //g.drawImage(img.getImage(), disNodo, 35, 170, 50, this);
//           
//            g.fillRect(50, disNodo , 160, 70);
//            disNodo += aumentoNodo;
//            
//            this.setSize(disNodo+200, 21); 
//            g.setColor(Color.black); 
//            g.drawString(String.valueOf(disNodo), 30, disNodo-10); 
//            g.drawString(String.valueOf(tp.get(i).dato.getLocalidad()), 30, disNombre);
//
//            this.repaint();
//            disNombre += aumentoNombre;
//        }

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
